PERIOD_CHOICES = {
	1: "1960 Sonrası Mistik Duyarlılık",
	2: "1980 Sonrası Roman-Öykü",
	3: "1980 Sonrası Şiir",
	4: "Bağımsız",
	5: "Beş Hececiler",
	6: "Bireyin İç Dünyasını Esas Alanlar",
	7: "Cumhuriyet Dönemi Öğretici Metinler",
	8: "Divan Edebiyatı",
	9: "Fecr-i Âti",
	10: "Garip Dışında Yenilikçi Şiir",
	11: "Garipçiler",
	12: "Göstermeye Bağlı Metinler",
	13: "Halk Şiiri",
	14: "İkinci Yeni",
	15: "İkinci Yeni Sonrası Toplumcu Şiir",
	16: "Maviciler",
	17: "Milli Edebiyat",
	18: "Milli Edebiyat Zevk ve Anlayışını Sürdürenler",
	19: "Modernizmi Esas Alanlar",
	20: "Öz Şiir Anlayışını Sürdürenler",
	21: "Postmodernizm",
	22: "Serbest Nazım ve Toplumcu Şiir",
	23: "Servet-i Fünun",
	24: "Tanzimat 1.Dönem",
	25: "Tanzimat 2.Dönem",
	26: "Yedi Meşaleciler"
}
