# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akim', models.CharField(max_length=100)),
                ('donem', models.CharField(max_length=100)),
                ('yazar', models.CharField(max_length=200)),
                ('eser', models.CharField(max_length=200)),
                ('tur', models.CharField(max_length=100)),
            ],
        ),
    ]
